apiVersion: apps/v1
kind: Deployment
metadata:
  name: devop-automation
spec:
  selector:
    matchLabels:
      app: devop-automation
  replicas: 2
  template:
    metadata:
      labels:
        app: devop-automation
    spec:
      containers:
        - name: devop-automation
          image: kyawtkshwesin/devop-automation:REPLACE_TAG
          ports:
            - containerPort: 8000