spring.application.name=devop-automation
server.port=8001
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=testdb

spring.mvc.servlet.path=/api/v1

# ===== Kafka Bootstrap =====
spring.kafka.bootstrap-servers=localhost:9092

# ===== Producer Configuration =====
# Use String keys
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# JSON-serialize your DTO values
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Trust the package where your DTOs live
spring.kafka.producer.properties.spring.json.trusted.packages=com.lattmat.devop.dto

# ===== Consumer Configuration =====
# Consumer group for this app
spring.kafka.consumer.group-id=default-group
# Use String keys
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# JSON-deserialize your DTO values
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# Trust the same DTO package
spring.kafka.consumer.properties.spring.json.trusted.packages=com.lattmat.devop.dto

# ===== (Optional) Listener Settings =====
# How many threads (and hence partitions) to consume in parallel
spring.kafka.listener.concurrency=3
# Don?t fail startup if a topic is missing
spring.kafka.listener.missing-topics-fatal=false
